function C = C_climber(in1,in2,in3)
%C_CLIMBER
%    C = C_CLIMBER(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-Nov-2020 06:11:58

y = in1(1,:);
C = y;
