function C = C_climber(in1,tau2,in3)
%C_CLIMBER
%    C = C_CLIMBER(IN1,TAU2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Nov-2020 21:05:46

y = in1(1,:);
C = y;
