function COM = COM_climber(in1,in2)
%COM_CLIMBER
%    COM = COM_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Nov-2020 15:44:30

L_BC = in2(8,:);
L_CE = in2(11,:);
L_EG = in2(12,:);
L_FH = in2(15,:);
L_GH = in2(16,:);
c_AB = in2(17,:);
c_BC = in2(18,:);
c_CE = in2(19,:);
c_DF = in2(21,:);
c_EG = in2(20,:);
c_FH = in2(22,:);
delta = in2(6,:);
dgam = in1(8,:);
dth1 = in1(6,:);
dth2 = in1(7,:);
dy = in1(5,:);
gam = in1(4,:);
m_AB = in2(23,:);
m_BC = in2(24,:);
m_CE = in2(25,:);
m_DF = in2(27,:);
m_EG = in2(26,:);
m_FH = in2(28,:);
m_motor = in2(30,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = cos(gam);
t3 = sin(gam);
t4 = gam+th1;
t5 = m_motor.*2.0;
t13 = -th2;
t6 = L_CE.*t2;
t7 = L_GH.*t2;
t8 = L_CE.*t3;
t9 = L_GH.*t3;
t10 = cos(t4);
t11 = delta+t4;
t12 = sin(t4);
t16 = gam+t13;
t21 = m_AB+m_BC+m_CE+m_DF+m_EG+m_FH+t5;
t14 = cos(t11);
t15 = sin(t11);
t17 = sin(t16);
t18 = cos(t16);
t22 = 1.0./t21;
t19 = L_EG.*t18;
t20 = L_EG.*t17;
COM = [t22.*(m_motor.*(t9+t20)+m_CE.*(t9+t20+c_CE.*t3)+m_DF.*(L_FH.*t3+c_DF.*t17)+m_motor.*(t8+t9+t20)+m_BC.*(t8+t9+t20+c_BC.*t12)+m_EG.*(t9+c_EG.*t17)+m_AB.*(t8+t9+t20+L_BC.*t12-c_AB.*t15)+c_FH.*m_FH.*t3);t22.*(m_motor.*(t6+t7+t19+y)+m_BC.*(t6+t7+t19+y+c_BC.*t10)+m_EG.*(t7+y+c_EG.*t18)+m_AB.*(t6+t7+t19+y+L_BC.*t10-c_AB.*t14)+m_motor.*(t7+t19+y)+m_CE.*(t7+t19+y+c_CE.*t2)+m_FH.*(y+c_FH.*t2)+m_DF.*(y+L_FH.*t2+c_DF.*t18));t22.*(dgam.*m_AB.*t6+dgam.*m_AB.*t7+dgam.*m_AB.*t19+dgam.*m_BC.*t6+dgam.*m_BC.*t7+dgam.*m_BC.*t19+dgam.*m_CE.*t7+dgam.*m_CE.*t19+dgam.*m_EG.*t7+dgam.*m_motor.*t6-dth2.*m_AB.*t19-dth2.*m_BC.*t19-dth2.*m_CE.*t19-dth2.*m_motor.*t19.*2.0+dgam.*t5.*t7+dgam.*t5.*t19-c_AB.*dgam.*m_AB.*t14+c_BC.*dgam.*m_BC.*t10+c_CE.*dgam.*m_CE.*t2+c_DF.*dgam.*m_DF.*t18+c_EG.*dgam.*m_EG.*t18+c_FH.*dgam.*m_FH.*t2-c_AB.*dth1.*m_AB.*t14+c_BC.*dth1.*m_BC.*t10-c_DF.*dth2.*m_DF.*t18-c_EG.*dth2.*m_EG.*t18+L_BC.*dgam.*m_AB.*t10+L_FH.*dgam.*m_DF.*t2+L_BC.*dth1.*m_AB.*t10);-t22.*(-dy.*m_AB-dy.*m_BC-dy.*m_CE-dy.*m_DF-dy.*m_EG-dy.*m_FH-dy.*m_motor.*2.0+dgam.*m_AB.*t8+dgam.*m_AB.*t9+dgam.*m_AB.*t20+dgam.*m_BC.*t8+dgam.*m_BC.*t9+dgam.*m_BC.*t20+dgam.*m_CE.*t9+dgam.*m_CE.*t20+dgam.*m_EG.*t9+dgam.*m_motor.*t8-dth2.*m_AB.*t20-dth2.*m_BC.*t20-dth2.*m_CE.*t20-dth2.*m_motor.*t20.*2.0+dgam.*t5.*t9+dgam.*t5.*t20-c_AB.*dgam.*m_AB.*t15+c_BC.*dgam.*m_BC.*t12+c_CE.*dgam.*m_CE.*t3+c_DF.*dgam.*m_DF.*t17+c_EG.*dgam.*m_EG.*t17+c_FH.*dgam.*m_FH.*t3-c_AB.*dth1.*m_AB.*t15+c_BC.*dth1.*m_BC.*t12-c_DF.*dth2.*m_DF.*t17-c_EG.*dth2.*m_EG.*t17+L_BC.*dgam.*m_AB.*t12+L_FH.*dgam.*m_DF.*t3+L_BC.*dth1.*m_AB.*t12)];
