function COM = COM_climber(in1,in2)
%COM_CLIMBER
%    COM = COM_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Nov-2020 21:05:48

L_BC = in2(8,:);
L_CE = in2(11,:);
L_EG = in2(12,:);
L_FH = in2(15,:);
L_GH = in2(16,:);
c_AB = in2(17,:);
c_BC = in2(18,:);
c_CE = in2(19,:);
c_DF = in2(21,:);
c_EG = in2(20,:);
c_FH = in2(22,:);
delta = in2(6,:);
dgam = in1(6,:);
dth2 = in1(5,:);
dy = in1(4,:);
gam = in1(3,:);
m_AB = in2(23,:);
m_BC = in2(24,:);
m_CE = in2(25,:);
m_DF = in2(27,:);
m_EG = in2(26,:);
m_FH = in2(28,:);
m_motor = in2(30,:);
th2 = in1(2,:);
y = in1(1,:);
t2 = cos(gam);
t3 = sin(gam);
t4 = gam+th2;
t5 = m_motor.*2.0;
t12 = -gam;
t6 = L_CE.*t2;
t7 = L_GH.*t2;
t8 = L_CE.*t3;
t9 = L_GH.*t3;
t10 = cos(t4);
t11 = sin(t4);
t15 = delta+t12;
t18 = m_AB+m_BC+m_CE+m_DF+m_EG+m_FH+t5;
t13 = L_EG.*t10;
t14 = L_EG.*t11;
t16 = cos(t15);
t17 = sin(t15);
t19 = 1.0./t18;
COM = [-t19.*(m_motor.*(t9+t14)+m_CE.*(t9+t14+c_CE.*t3)+m_DF.*(L_FH.*t3+c_DF.*t11)+m_motor.*(t8+t9+t14)+m_BC.*(t8+t9+t14+c_BC.*t3)+m_EG.*(t9+c_EG.*t11)+m_AB.*(t8+t9+t14+L_BC.*t3+c_AB.*t17)+c_FH.*m_FH.*t3);t19.*(m_motor.*(t6+t7+t13+y)+m_BC.*(t6+t7+t13+y+c_BC.*t2)+m_EG.*(t7+y+c_EG.*t10)+m_AB.*(t6+t7+t13+y+L_BC.*t2-c_AB.*t16)+m_motor.*(t7+t13+y)+m_CE.*(t7+t13+y+c_CE.*t2)+m_FH.*(y+c_FH.*t2)+m_DF.*(y+L_FH.*t2+c_DF.*t10));-dgam.*t19.*(m_AB.*t6+m_AB.*t7+m_AB.*t13+m_BC.*t6+m_BC.*t7+m_BC.*t13+m_CE.*t7+m_CE.*t13+m_EG.*t7+m_motor.*t6+t5.*t7+t5.*t13+L_BC.*m_AB.*t2+L_FH.*m_DF.*t2-c_AB.*m_AB.*t16+c_BC.*m_BC.*t2+c_CE.*m_CE.*t2+c_DF.*m_DF.*t10+c_EG.*m_EG.*t10+c_FH.*m_FH.*t2)-dth2.*t10.*t19.*(L_EG.*m_AB+L_EG.*m_BC+L_EG.*m_CE+L_EG.*t5+c_DF.*m_DF+c_EG.*m_EG);-t19.*(-dy.*m_AB-dy.*m_BC-dy.*m_CE-dy.*m_DF-dy.*m_EG-dy.*m_FH-dy.*m_motor.*2.0+dgam.*m_AB.*t8+dgam.*m_AB.*t9+dgam.*m_AB.*t14+dgam.*m_BC.*t8+dgam.*m_BC.*t9+dgam.*m_BC.*t14+dgam.*m_CE.*t9+dgam.*m_CE.*t14+dgam.*m_EG.*t9+dgam.*m_motor.*t8+dth2.*m_AB.*t14+dth2.*m_BC.*t14+dth2.*m_CE.*t14+dgam.*t5.*t9+dgam.*t5.*t14+dth2.*t5.*t14+c_AB.*dgam.*m_AB.*t17+c_BC.*dgam.*m_BC.*t3+c_CE.*dgam.*m_CE.*t3+c_DF.*dgam.*m_DF.*t11+c_EG.*dgam.*m_EG.*t11+c_FH.*dgam.*m_FH.*t3+c_DF.*dth2.*m_DF.*t11+c_EG.*dth2.*m_EG.*t11+L_BC.*dgam.*m_AB.*t3+L_FH.*dgam.*m_DF.*t3)];
