function Corr_Joint_Sp = corr_climber(in1,in2)
%CORR_CLIMBER
%    CORR_JOINT_SP = CORR_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Nov-2020 21:05:53

L_BC = in2(8,:);
L_CE = in2(11,:);
L_EG = in2(12,:);
L_FH = in2(15,:);
L_GH = in2(16,:);
c_AB = in2(17,:);
c_BC = in2(18,:);
c_CE = in2(19,:);
c_DF = in2(21,:);
c_EG = in2(20,:);
c_FH = in2(22,:);
delta = in2(6,:);
dgam = in1(6,:);
dth2 = in1(5,:);
gam = in1(3,:);
m_AB = in2(23,:);
m_BC = in2(24,:);
m_CE = in2(25,:);
m_DF = in2(27,:);
m_EG = in2(26,:);
m_FH = in2(28,:);
m_motor = in2(30,:);
th2 = in1(2,:);
t2 = cos(gam);
t3 = sin(th2);
t4 = delta+th2;
t5 = gam+th2;
t6 = dgam.^2;
t7 = dth2.^2;
t8 = cos(t5);
t9 = sin(t4);
t10 = L_BC.*L_EG.*m_AB.*t3;
t11 = L_CE.*L_EG.*m_AB.*t3;
t12 = L_CE.*L_EG.*m_BC.*t3;
t13 = L_EG.*L_GH.*m_AB.*t3;
t14 = L_EG.*L_GH.*m_BC.*t3;
t15 = L_EG.*L_GH.*m_CE.*t3;
t16 = L_CE.*L_EG.*m_motor.*t3;
t17 = L_EG.*c_BC.*m_BC.*t3;
t18 = L_EG.*c_CE.*m_CE.*t3;
t19 = L_FH.*c_DF.*m_DF.*t3;
t20 = L_GH.*c_EG.*m_EG.*t3;
t21 = L_EG.*L_GH.*m_motor.*t3.*2.0;
t22 = L_EG.*c_AB.*m_AB.*t9;
t23 = -t22;
t24 = t10+t11+t12+t13+t14+t15+t16+t17+t18+t19+t20+t21+t23;
Corr_Joint_Sp = [-L_BC.*m_AB.*t2.*t6-L_CE.*m_AB.*t2.*t6-L_CE.*m_BC.*t2.*t6-L_EG.*m_AB.*t6.*t8-L_EG.*m_AB.*t7.*t8-L_EG.*m_BC.*t6.*t8-L_EG.*m_BC.*t7.*t8-L_GH.*m_AB.*t2.*t6-L_EG.*m_CE.*t6.*t8-L_EG.*m_CE.*t7.*t8-L_GH.*m_BC.*t2.*t6-L_GH.*m_CE.*t2.*t6-L_FH.*m_DF.*t2.*t6-L_GH.*m_EG.*t2.*t6-L_CE.*m_motor.*t2.*t6-L_EG.*m_motor.*t6.*t8.*2.0-L_EG.*m_motor.*t7.*t8.*2.0-L_GH.*m_motor.*t2.*t6.*2.0-c_BC.*m_BC.*t2.*t6-c_CE.*m_CE.*t2.*t6-c_DF.*m_DF.*t6.*t8-c_DF.*m_DF.*t7.*t8-c_EG.*m_EG.*t6.*t8-c_EG.*m_EG.*t7.*t8-c_FH.*m_FH.*t2.*t6+c_AB.*m_AB.*t6.*cos(delta-gam)-L_EG.*dgam.*dth2.*m_AB.*t8.*2.0-L_EG.*dgam.*dth2.*m_BC.*t8.*2.0-L_EG.*dgam.*dth2.*m_CE.*t8.*2.0-L_EG.*dgam.*dth2.*m_motor.*t8.*4.0-c_DF.*dgam.*dth2.*m_DF.*t8.*2.0-c_EG.*dgam.*dth2.*m_EG.*t8.*2.0;t6.*t24;-dth2.*t24.*(dgam.*2.0+dth2)];
