function dC = dC_climber(in1,tau2,in3)
%DC_CLIMBER
%    DC = DC_CLIMBER(IN1,TAU2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Nov-2020 21:05:47

dy = in1(4,:);
dC = dy;
