function dC = dC_climber(in1,in2,in3)
%DC_CLIMBER
%    DC = DC_CLIMBER(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Nov-2020 15:44:29

dy = in1(5,:);
dC = dy;
