function dkeypoints = dkeypoints_climber(in1,in2)
%DKEYPOINTS_CLIMBER
%    DKEYPOINTS = DKEYPOINTS_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Nov-2020 21:05:46

L_AB = in2(7,:);
L_BC = in2(8,:);
L_CE = in2(11,:);
L_DF = in2(13,:);
L_EG = in2(12,:);
L_FH = in2(15,:);
L_GH = in2(16,:);
delta = in2(6,:);
dgam = in1(6,:);
dth2 = in1(5,:);
dy = in1(4,:);
gam = in1(3,:);
th2 = in1(2,:);
t2 = cos(gam);
t3 = sin(gam);
t4 = gam+th2;
t13 = -gam;
t5 = L_BC.*t2;
t6 = L_CE.*t2;
t7 = L_GH.*t2;
t8 = L_BC.*t3;
t9 = L_CE.*t3;
t10 = L_GH.*t3;
t11 = cos(t4);
t12 = sin(t4);
t16 = delta+t13;
t14 = L_EG.*t11;
t15 = L_EG.*t12;
t17 = dth2.*t14;
t18 = dth2.*t15;
t19 = -t17;
t20 = -t18;
dkeypoints = reshape([t19-dgam.*(t5+t6+t7+t14-L_AB.*cos(t16)),dy+t20-dgam.*(t8+t9+t10+t15+L_AB.*sin(t16)),0.0,t19-dgam.*(t5+t6+t7+t14),dy+t20-dgam.*(t8+t9+t10+t15),0.0,t19-dgam.*(t6+t7+t14),dy+t20-dgam.*(t9+t10+t15),0.0,-dgam.*(L_DF.*t11+L_FH.*t2)-L_DF.*dth2.*t11,dy-dgam.*(L_DF.*t12+L_FH.*t3)-L_DF.*dth2.*t12,0.0,t19-dgam.*(t7+t14),dy+t20-dgam.*(t10+t15),0.0,-L_FH.*dgam.*t2,dy-L_FH.*dgam.*t3,0.0,-dgam.*t7,dy-dgam.*t10,0.0,0.0,dy,0.0],[3,8]);
