function dkeypoints = dkeypoints_climber(in1,in2)
%DKEYPOINTS_CLIMBER
%    DKEYPOINTS = DKEYPOINTS_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Nov-2020 15:44:28

L_AB = in2(7,:);
L_BC = in2(8,:);
L_CE = in2(11,:);
L_DF = in2(13,:);
L_EG = in2(12,:);
L_FH = in2(15,:);
L_GH = in2(16,:);
delta = in2(6,:);
dgam = in1(8,:);
dth1 = in1(6,:);
dth2 = in1(7,:);
dy = in1(5,:);
gam = in1(4,:);
th1 = in1(2,:);
th2 = in1(3,:);
t2 = cos(gam);
t3 = sin(gam);
t4 = gam+th1;
t12 = -th2;
t5 = L_CE.*t2;
t6 = L_GH.*t2;
t7 = L_CE.*t3;
t8 = L_GH.*t3;
t9 = cos(t4);
t10 = delta+t4;
t11 = sin(t4);
t17 = gam+t12;
t13 = cos(t10);
t14 = sin(t10);
t15 = L_BC.*t9;
t16 = L_BC.*t11;
t18 = sin(t17);
t21 = cos(t17);
t19 = L_AB.*t13;
t20 = L_AB.*t14;
t22 = L_EG.*t21;
t24 = L_EG.*t18;
t23 = -t19;
t25 = -t20;
t26 = dth2.*t22;
t27 = dth2.*t24;
t28 = -t26;
dkeypoints = reshape([t28+dth1.*(t15+t23)+dgam.*(t5+t6+t15+t22+t23),dy+t27-dth1.*(t16+t25)-dgam.*(t7+t8+t16+t24+t25),0.0,t28+dth1.*t15+dgam.*(t5+t6+t15+t22),dy+t27-dth1.*t16-dgam.*(t7+t8+t16+t24),0.0,t28+dgam.*(t5+t6+t22),dy+t27-dgam.*(t7+t8+t24),0.0,dgam.*(L_DF.*t21+L_FH.*t2)-L_DF.*dth2.*t21,dy-dgam.*(L_DF.*t18+L_FH.*t3)+L_DF.*dth2.*t18,0.0,t28+dgam.*(t6+t22),dy+t27-dgam.*(t8+t24),0.0,L_FH.*dgam.*t2,dy-L_FH.*dgam.*t3,0.0,dgam.*t6,dy-dgam.*t8,0.0,0.0,dy,0.0],[3,8]);
