function dkeypoints = dkeypoints_climber(in1,in2)
%DKEYPOINTS_CLIMBER
%    DKEYPOINTS = DKEYPOINTS_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Nov-2020 20:54:18

L_AB = in2(7,:);
L_BC = in2(8,:);
L_CE = in2(11,:);
L_DF = in2(13,:);
L_EG = in2(12,:);
L_FH = in2(15,:);
L_GH = in2(16,:);
delta = in2(6,:);
dgam = in1(8,:);
dth1 = in1(6,:);
dth2 = in1(7,:);
dy = in1(5,:);
gam = in1(4,:);
th1 = in1(2,:);
th2 = in1(3,:);
t2 = cos(gam);
t3 = sin(gam);
t4 = gam+th2;
t11 = -gam;
t12 = -th1;
t5 = L_CE.*t2;
t6 = L_GH.*t2;
t7 = L_CE.*t3;
t8 = L_GH.*t3;
t9 = cos(t4);
t10 = sin(t4);
t15 = gam+t12;
t20 = delta+t11+th1;
t13 = L_EG.*t9;
t14 = L_EG.*t10;
t16 = sin(t15);
t19 = cos(t15);
t21 = cos(t20);
t22 = sin(t20);
t17 = dth2.*t13;
t18 = dth2.*t14;
t23 = L_BC.*t19;
t25 = L_BC.*t16;
t27 = L_AB.*t21;
t28 = L_AB.*t22;
t24 = -t17;
t26 = -t18;
dkeypoints = reshape([t24+dth1.*(t23-t27)-dgam.*(t5+t6+t13+t23-t27),dy+t26+dth1.*(t25+t28)-dgam.*(t7+t8+t14+t25+t28),0.0,t24+dth1.*t23-dgam.*(t5+t6+t13+t23),dy+t26+dth1.*t25-dgam.*(t7+t8+t14+t25),0.0,t24-dgam.*(t5+t6+t13),dy+t26-dgam.*(t7+t8+t14),0.0,-dgam.*(L_DF.*t9+L_FH.*t2)-L_DF.*dth2.*t9,dy-dgam.*(L_DF.*t10+L_FH.*t3)-L_DF.*dth2.*t10,0.0,t24-dgam.*(t6+t13),dy+t26-dgam.*(t8+t14),0.0,-L_FH.*dgam.*t2,dy-L_FH.*dgam.*t3,0.0,-dgam.*t6,dy-dgam.*t8,0.0,0.0,dy,0.0],[3,8]);
