function Grav_Joint_Sp = grav_climber(in1,in2)
%GRAV_CLIMBER
%    GRAV_JOINT_SP = GRAV_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Nov-2020 21:05:53

L_BC = in2(8,:);
L_CE = in2(11,:);
L_EG = in2(12,:);
L_FH = in2(15,:);
L_GH = in2(16,:);
c_AB = in2(17,:);
c_BC = in2(18,:);
c_CE = in2(19,:);
c_DF = in2(21,:);
c_EG = in2(20,:);
c_FH = in2(22,:);
delta = in2(6,:);
g = in2(1,:);
gam = in1(3,:);
m_AB = in2(23,:);
m_BC = in2(24,:);
m_CE = in2(25,:);
m_DF = in2(27,:);
m_EG = in2(26,:);
m_FH = in2(28,:);
m_motor = in2(30,:);
th2 = in1(2,:);
t2 = sin(gam);
t3 = gam+th2;
t4 = sin(t3);
Grav_Joint_Sp = [g.*(m_AB+m_BC+m_CE+m_DF+m_EG+m_FH+m_motor.*2.0);-g.*t4.*(L_EG.*m_AB+L_EG.*m_BC+L_EG.*m_CE+L_EG.*m_motor.*2.0+c_DF.*m_DF+c_EG.*m_EG);-g.*(c_AB.*m_AB.*sin(delta-gam)+L_BC.*m_AB.*t2+L_CE.*m_AB.*t2+L_CE.*m_BC.*t2+L_EG.*m_AB.*t4+L_EG.*m_BC.*t4+L_GH.*m_AB.*t2+L_EG.*m_CE.*t4+L_GH.*m_BC.*t2+L_GH.*m_CE.*t2+L_FH.*m_DF.*t2+L_GH.*m_EG.*t2+L_CE.*m_motor.*t2+L_EG.*m_motor.*t4.*2.0+L_GH.*m_motor.*t2.*2.0+c_BC.*m_BC.*t2+c_CE.*m_CE.*t2+c_DF.*m_DF.*t4+c_EG.*m_EG.*t4+c_FH.*m_FH.*t2)];
