function jH = jacobian_foot_climber(in1,in2)
%JACOBIAN_FOOT_CLIMBER
%    JH = JACOBIAN_FOOT_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Nov-2020 21:05:52

jH = reshape([0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
