function jA = jacobian_hand_climber(in1,in2)
%JACOBIAN_HAND_CLIMBER
%    JA = JACOBIAN_HAND_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Nov-2020 15:44:41

L_AB = in2(7,:);
L_BC = in2(8,:);
L_CE = in2(11,:);
L_EG = in2(12,:);
L_GH = in2(16,:);
delta = in2(6,:);
gam = in1(4,:);
th1 = in1(2,:);
th2 = in1(3,:);
t2 = cos(gam);
t3 = sin(gam);
t4 = gam+th1;
t8 = -th2;
t5 = cos(t4);
t6 = delta+t4;
t7 = sin(t4);
t13 = gam+t8;
t9 = cos(t6);
t10 = sin(t6);
t11 = L_BC.*t5;
t12 = L_BC.*t7;
t14 = sin(t13);
t17 = cos(t13);
t15 = L_AB.*t9;
t16 = L_AB.*t10;
t18 = -t12;
t19 = L_EG.*t17;
t21 = L_EG.*t14;
t20 = -t15;
jA = reshape([0.0,1.0,0.0,t11+t20,t16+t18,0.0,-t19,t21,0.0,t11+t19+t20+L_CE.*t2+L_GH.*t2,t16+t18-t21-L_CE.*t3-L_GH.*t3,0.0],[3,4]);
