function jA = jacobian_hand_climber(in1,in2)
%JACOBIAN_HAND_CLIMBER
%    JA = JACOBIAN_HAND_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Nov-2020 20:54:28

L_AB = in2(7,:);
L_BC = in2(8,:);
L_CE = in2(11,:);
L_EG = in2(12,:);
L_GH = in2(16,:);
delta = in2(6,:);
gam = in1(4,:);
th1 = in1(2,:);
th2 = in1(3,:);
t2 = cos(gam);
t3 = sin(gam);
t4 = gam+th2;
t7 = -gam;
t8 = -th1;
t5 = cos(t4);
t6 = sin(t4);
t11 = gam+t8;
t14 = delta+t7+th1;
t9 = L_EG.*t5;
t10 = L_EG.*t6;
t12 = sin(t11);
t13 = cos(t11);
t17 = cos(t14);
t18 = sin(t14);
t15 = -t9;
t16 = -t10;
t19 = L_BC.*t13;
t20 = L_BC.*t12;
t21 = L_AB.*t17;
t22 = L_AB.*t18;
jA = reshape([0.0,1.0,0.0,t19-t21,t20+t22,0.0,t15,t16,0.0,t15-t19+t21-L_CE.*t2-L_GH.*t2,t16-t20-t22-L_CE.*t3-L_GH.*t3,0.0],[3,4]);
