function djH = jacobian_dot_foot_climber(in1,in2)
%JACOBIAN_DOT_FOOT_CLIMBER
%    DJH = JACOBIAN_DOT_FOOT_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Nov-2020 15:44:42

djH = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,4]);
