function jA = jacobian_hand_climber(in1,in2)
%JACOBIAN_HAND_CLIMBER
%    JA = JACOBIAN_HAND_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Nov-2020 21:05:52

L_AB = in2(7,:);
L_BC = in2(8,:);
L_CE = in2(11,:);
L_EG = in2(12,:);
L_GH = in2(16,:);
delta = in2(6,:);
gam = in1(3,:);
th2 = in1(2,:);
t2 = cos(gam);
t3 = sin(gam);
t4 = gam+th2;
t7 = -gam;
t5 = cos(t4);
t6 = sin(t4);
t10 = delta+t7;
t8 = L_EG.*t5;
t9 = L_EG.*t6;
t11 = -t8;
t12 = -t9;
jA = reshape([0.0,1.0,0.0,t11,t12,0.0,t11-L_BC.*t2-L_CE.*t2-L_GH.*t2+L_AB.*cos(t10),t12-L_BC.*t3-L_CE.*t3-L_GH.*t3-L_AB.*sin(t10),0.0],[3,3]);
