function jC = jacobian_C_climber(in1,in2)
%JACOBIAN_C_CLIMBER
%    JC = JACOBIAN_C_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Nov-2020 15:44:42

L_CE = in2(11,:);
L_EG = in2(12,:);
L_GH = in2(16,:);
gam = in1(4,:);
th2 = in1(3,:);
t2 = cos(gam);
t3 = sin(gam);
t4 = -th2;
t5 = gam+t4;
t6 = sin(t5);
t7 = cos(t5);
t8 = L_EG.*t7;
t9 = L_EG.*t6;
jC = reshape([0.0,1.0,0.0,0.0,0.0,0.0,-t8,t9,0.0,t8+L_CE.*t2+L_GH.*t2,-t9-L_CE.*t3-L_GH.*t3,0.0],[3,4]);
