function jC = jacobian_C_climber(in1,in2)
%JACOBIAN_C_CLIMBER
%    JC = JACOBIAN_C_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Nov-2020 21:05:52

L_CE = in2(11,:);
L_EG = in2(12,:);
L_GH = in2(16,:);
gam = in1(3,:);
th2 = in1(2,:);
t2 = cos(gam);
t3 = sin(gam);
t4 = gam+th2;
t5 = cos(t4);
t6 = sin(t4);
t7 = L_EG.*t5;
t8 = L_EG.*t6;
t9 = -t7;
t10 = -t8;
jC = reshape([0.0,1.0,0.0,t9,t10,0.0,t9-L_CE.*t2-L_GH.*t2,t10-L_CE.*t3-L_GH.*t3,0.0],[3,3]);
