function keypoints = keypoints_climber(in1,in2)
%KEYPOINTS_CLIMBER
%    KEYPOINTS = KEYPOINTS_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Nov-2020 09:58:37

L_AB = in2(7,:);
L_BC = in2(8,:);
L_CE = in2(11,:);
L_DF = in2(13,:);
L_EG = in2(12,:);
L_FH = in2(15,:);
L_GH = in2(16,:);
delta = in2(6,:);
gam = in1(4,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = cos(gam);
t3 = sin(gam);
t4 = gam+th2;
t13 = -th1;
t5 = L_CE.*t2;
t6 = L_FH.*t2;
t7 = L_GH.*t2;
t8 = L_CE.*t3;
t9 = L_FH.*t3;
t10 = L_GH.*t3;
t11 = cos(t4);
t12 = sin(t4);
t16 = gam+t13;
t14 = L_EG.*t11;
t15 = L_EG.*t12;
t17 = sin(t16);
t18 = cos(t16);
t19 = delta+t16;
t20 = L_BC.*t18;
t21 = L_BC.*t17;
keypoints = reshape([t8+t10+t15+t21-L_AB.*sin(t19),t5+t7+t14+t20+y-L_AB.*cos(t19),0.0,t8+t10+t15+t21,t5+t7+t14+t20+y,0.0,t8+t10+t15,t5+t7+t14+y,0.0,t9+L_DF.*t12,t6+y+L_DF.*t11,0.0,t10+t15,t7+t14+y,0.0,t9,t6+y,0.0,t10,t7+y,0.0,0.0,y,0.0],[3,8]);
