function keypoints = keypoints_climber(in1,in2)
%KEYPOINTS_CLIMBER
%    KEYPOINTS = KEYPOINTS_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-Nov-2020 06:11:58

L_AB = in2(7,:);
L_BC = in2(8,:);
L_CE = in2(11,:);
L_DF = in2(13,:);
L_EG = in2(12,:);
L_FH = in2(15,:);
L_GH = in2(16,:);
delta = in2(6,:);
phi = in1(4,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = cos(phi);
t3 = sin(phi);
t4 = delta+phi;
t5 = phi+th1;
t6 = L_BC.*t2;
t7 = L_BC.*t3;
t8 = cos(t5);
t9 = sin(t5);
t10 = t5+th2;
t11 = cos(t10);
t12 = sin(t10);
t13 = L_CE.*t8;
t14 = L_FH.*t8;
t15 = L_GH.*t8;
t16 = L_CE.*t9;
t17 = L_FH.*t9;
t18 = L_GH.*t9;
t19 = L_EG.*t11;
t20 = L_EG.*t12;
keypoints = reshape([t7+t16+t18+t20-L_AB.*sin(t4),t6+t13+t15+t19+y-L_AB.*cos(t4),0.0,t7+t16+t18+t20,t6+t13+t15+t19+y,0.0,t16+t18+t20,t13+t15+t19+y,0.0,t17+L_DF.*t12,t14+y+L_DF.*t11,0.0,t18+t20,t15+t19+y,0.0,t17,t14+y,0.0,t18,t15+y,0.0,0.0,y,0.0],[3,8]);
