function keypoints = keypoints_climber(in1,in2)
%KEYPOINTS_CLIMBER
%    KEYPOINTS = KEYPOINTS_CLIMBER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Nov-2020 15:44:27

L_AB = in2(7,:);
L_BC = in2(8,:);
L_CE = in2(11,:);
L_DF = in2(13,:);
L_EG = in2(12,:);
L_FH = in2(15,:);
L_GH = in2(16,:);
delta = in2(6,:);
gam = in1(4,:);
th1 = in1(2,:);
th2 = in1(3,:);
y = in1(1,:);
t2 = cos(gam);
t3 = sin(gam);
t4 = gam+th1;
t14 = -th2;
t5 = L_CE.*t2;
t6 = L_FH.*t2;
t7 = L_GH.*t2;
t8 = L_CE.*t3;
t9 = L_FH.*t3;
t10 = L_GH.*t3;
t11 = cos(t4);
t12 = delta+t4;
t13 = sin(t4);
t17 = gam+t14;
t15 = L_BC.*t11;
t16 = L_BC.*t13;
t18 = sin(t17);
t19 = cos(t17);
t20 = L_EG.*t19;
t21 = L_EG.*t18;
keypoints = reshape([t8+t10+t16+t21-L_AB.*sin(t12),t5+t7+t15+t20+y-L_AB.*cos(t12),0.0,t8+t10+t16+t21,t5+t7+t15+t20+y,0.0,t8+t10+t21,t5+t7+t20+y,0.0,t9+L_DF.*t18,t6+y+L_DF.*t19,0.0,t10+t21,t7+t20+y,0.0,t9,t6+y,0.0,t10,t7+y,0.0,0.0,y,0.0],[3,8]);
